blank_issues_enabled: false

contact_links:
  - name: ğŸ‰ Contributing Guide
    url: https://github.com/paduszyk/python-gitmojis/blob/main/.github/CONTRIBUTING.md
    about: |
      Please read through before making any contribution.
  - name: ğŸ¤ Code of Conduct
    url: https://github.com/paduszyk/python-gitmojis/blob/main/.github/CODE_OF_CONDUCT.md
    about: |
      All contributors must agree to follow our code of conduct.
  - name: ğŸ‘¥ GitHub Community Guidelines
    url: https://docs.github.com/en/site-policy/github-terms/github-community-guidelines
    about: |
      The article discussing GitHub's rules for user behavior and community conduct.
